FORMAT: 1A
HOST: http://www.lan.com

# Flight Status LATAM
Flight Status LATAM API provee información de status de vuelos LATAM.



## Flight Status Information By Origin & Destination [/ws/api/flight-status/1.0/rest/origin-destination/information/airline-code/{airlineCode}/departure-airport-code/{departureAirportCode}/arrival-airport-code/{arrivalAirportCode}/standar-time-condition/{standardTimeCondition}/date-time-from/{dateTimeFrom}/date-time-to/{dateTimeTo}/language/{language}/country/{country}]

+ Parameters
    + airlineCode (required, String, `ALL`) ...  `IATA Airline Code`  accepted values LAN, TAM, ALL, LA, 4M, XL, JJ, PZ.
    + departureAirportCode (required, String, `SCL`) ...  `Airport Departure IATA Code`.
    + arrivalAirportCode (required, String, `MIA`) ...  `Airport Arrival IATA Code`.
    + standardTimeCondition (required, String, `SCHEDULE`) ...  `Departure DateTime Condition to be Requested` accepted values SCHEDULE, REAL.
    + dateTimeFrom (required, DateTime, `2014-08-20T00:00:00`) ... `Local Date Time from period Requested for UTC Time Zone add Z` pattern YYYY-MM-DDThh:mm:ss or YYYY-MM-DDThh:mm:ssZ
    + dateTimeTo (required, DateTime, `2014-08-20T00:23:59:00`) ... `Local Date Time to period Requested for UTC Time Zone add Z` pattern YYYY-MM-DDThh:mm:ss or YYYY-MM-DDThh:mm:ssZ
    + language (required, String, `es`) ...  `language for message translation `  accepted values es, pt, en, de, fr, it
    + country (required, String, `cl`) ...  `country for message translation`  accepted values ar, cl, br, co, ec, pe, uy, py, us, mx, ca, de, es, fr, uk, ue, au, nz, un
    

### Retrieve a Flight Status Information By Origin & Destination [GET]

+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body
    
            {
                "status": {
                    "code": "0",
                    "message": "Message",
                    "nativeMessage": "Native Message"
                },
                "data": {
                    "flights": [
                        {
                            "airlineCode": "LA",
                            "flightNumber": "500",
                            "flightDate": "2014-08-20",
                            "legs": [
                                {
                                    "airlineCodes": {
                                        "operating": "LA",
                                        "marketing": "LA",
                                        "owner": "LA"
                                    },
                                    "departure": {
                                        "airportCode": "SCL",
                                        "blockOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "takeOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "arrival": {
                                        "airportCode": "MIA",
                                        "touchDown": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "blockOn": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "flightServiceType": {
                                        "code": "J",
                                        "description": "Passenger Normal Service",
                                        "routeTypeCode": "INT"
                                    },
                                    "material": {
                                        "aircraftRegistration": "CC-BBD",
                                        "fleet": "B787",
                                        "model": "800"
                                    },
                                    "statusCode": "AA",
                                    "descriptionStatusCode": "Descripcion Status Code AA",
                                    "operationStatusCode": "AA",
                                    "descriptionOperationStatusCode": "Descripcion Operation Status Code AA",
                                    "sufixCode": "AA",
                                    "descriptionSufixCode": "Descripcion Sufix Code AA",
                                    "operationalContingency": [
                                        {
                                            "departureAirportIataCode": "SCL",
                                            "contingencyType": "DELAY",
                                            "contingencyDescription": "Esto es un Atraso",
                                            "statusLog": [
                                                {
                                                    "statusDateTime": "2014-07-27T09:44:36",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-07-27T09:44:36",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-07-25T09:44:36"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-07-25T09:44:36"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                },
                                                {
                                                    "statusDateTime": "2014-07-25T09:44:36",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-07-25T09:44:36",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-07-25T09:44:36"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-07-25T09:44:36"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                }
                                            ],
                                            "protections": [
                                                {
                                                    "airlineCode": "4M",
                                                    "flightNumber": "465",
                                                    "flightDate": "2014-07-25",
                                                    "departureAirportIataCode": "SCL"
                                                },
                                                {
                                                    "airlineCode": "4M",
                                                    "flightNumber": "465",
                                                    "flightDate": "2014-07-25",
                                                    "departureAirportIataCode": "SCL"
                                                }
                                            ]
                                        }
                                    ],
                                    "gateInformation": {
                                        "gateNumber": "17",
                                        "gateDescription": "Puerta de Embarque 17"
                                    }
                                },
                                {
                                    "airlineCodes": {
                                        "operating": "LA",
                                        "marketing": "LA",
                                        "owner": "LA"
                                    },
                                    "departure": {
                                        "airportCode": "SCL",
                                        "blockOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "takeOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "arrival": {
                                        "airportCode": "MIA",
                                        "touchDown": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "blockOn": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "flightServiceType": {
                                        "code": "J",
                                        "description": "Passenger Normal Service",
                                        "routeTypeCode": "INT"
                                    },
                                    "material": {
                                        "aircraftRegistration": "CC-BBD",
                                        "fleet": "B787",
                                        "model": "800"
                                    },
                                    "statusCode": "AA",
                                    "descriptionStatusCode": "Descripcion Status Code AA",
                                    "operationStatusCode": "AA",
                                    "descriptionOperationStatusCode": "Descripcion Operation Status Code AA",
                                    "sufixCode": "AA",
                                    "descriptionSufixCode": "Descripcion Sufix Code AA",
                                    "operationalContingency": [
                                        {
                                            "departureAirportIataCode": "SCL",
                                            "contingencyType": "DELAY",
                                            "contingencyDescription": "Esto es un Atraso",
                                            "statusLog": [
                                                {
                                                    "statusDateTime": "2014-08-20T10:40",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-08-20T10:40",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                },
                                                {
                                                    "statusDateTime": "25-07-2014 09:44:36",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-08-20T10:40",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                }
                                            ],
                                            "protections": [
                                                {
                                                    "airlineCode": "4M",
                                                    "flightNumber": "465",
                                                    "flightDate": "2014-08-20",
                                                    "departureAirportIataCode": "SCL"
                                                },
                                                {
                                                    "airlineCode": "4M",
                                                    "flightNumber": "465",
                                                    "flightDate": "2014-08-20",
                                                    "departureAirportIataCode": "SCL"
                                                }
                                            ]
                                        }
                                    ],
                                    "gateInformation": {
                                        "gateNumber": "17",
                                        "gateDescription": "Puerta de Embarque 17"
                                    }
                                }
                            ]
                        },
                        {
                            "airlineCode": "JJ",
                            "flightNumber": "8029",
                            "flightDate": "20-08-2014",
                            "legs": [
                                {
                                    "airlineCodes": {
                                        "operating": "JJ",
                                        "marketing": "JJ",
                                        "owner": "JJ"
                                    },
                                    "departure": {
                                        "airportCode": "SCL",
                                        "blockOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "takeOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "arrival": {
                                        "airportCode": "GRU",
                                        "touchDown": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "blockOn": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "flightServiceType": {
                                        "code": "J",
                                        "description": "Passenger Normal Service",
                                        "routeTypeCode": "INT"
                                    },
                                    "material": {
                                        "aircraftRegistration": "PR-MAZ",
                                        "fleet": "A320",
                                        "model": "200"
                                    },
                                    "statusCode": "AA",
                                    "descriptionStatusCode": "Descripcion Status Code AA",
                                    "operationStatusCode": "AA",
                                    "descriptionOperationStatusCode": "Descripcion Operation Status Code AA",
                                    "sufixCode": "AA",
                                    "descriptionSufixCode": "Descripcion Sufix Code AA",
                                    "operationalContingency": [
                                        {
                                            "departureAirportIataCode": "SCL",
                                            "contingencyType": "DELAY",
                                            "contingencyDescription": "Esto es un Atraso",
                                            "statusLog": [
                                                {
                                                    "statusDateTime": "2014-08-20T10:40",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-08-20T10:40",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                },
                                                {
                                                    "statusDateTime": "2014-08-20T10:40",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-08-20T10:40",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                }
                                            ],
                                            "protections": [
                                                {
                                                    "airlineCode": "XL",
                                                    "flightNumber": "100",
                                                    "flightDate": "2014-08-20",
                                                    "departureAirportCode": "SCL"
                                                },
                                                {
                                                    "airlineCode": "XL",
                                                    "flightNumber": "101",
                                                    "flightDate": "2014-08-20",
                                                    "departureAirportCode": "SCL"
                                                }
                                            ]
                                        }
                                    ],
                                    "gateInformation": {
                                        "gateNumber": "190",
                                        "gateDescription": "Puerta de Embarque 190"
                                    }
                                }
                            ]
                        }
                    ]
                }
            }

                    
        

   
+ Response 500 (application/json)

    + Header

            X-My-Header: The Value
            
    + Body   
    
            {
                "status": {
                    "code": "500",
                    "message": "ERROR",
                    "nativeMessage": "Runtime Exception"
                }
            }
                
            
## Flight Status Information By Flight Number [/ws/api/flight-status/1.0/rest/flight-number/information/airline/{airline}/flight-number/{flightNumber}/departure-condition/{departureCondition}/time-standard/{timeStandard}/departure-date/{departureDate}/language/{language}/country/{country}]

+ Parameters
    + airline (required, String, `LAN`) ...  `Airline Code`  accepted values LAN, TAM.
    + flightNumber (required, string, `500`) ... String `Flight Number Requested`.
    + departureCondition (required, String, `SCHEDULE`) ...  `Departure DateTime Condition to be Requested` accepted values SCHEDULE, REAL.
    + timeStandard (required, String, `LOCAL`) ...  `Time Standard to be Requested` accepted values LOCAL, UTC.
    + departureDate (required, Date, `2014-08-20`) ...  `Departure Date for Flight Requested` pattern YYYY-MM-DD
    + language (required, String, `es`) ...  `language for message translation `  accepted values es, pt, en, de, fr, it
    + country (required, String, `cl`) ...  `country for message translation`  accepted values ar, cl, br, co, ec, pe, uy, py, us, mx, ca, de, es, fr, uk, ue, au, nz, un
    
    

### Retrieve a Flight Status Information By Flight Number [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body
            
            {
                "status": {
                    "code": "0",
                    "message": "Message",
                    "nativeMessage": "Native Message"
                },
                "data": {
                    "flights": [
                        {
                            "airlineCode": "LA",
                            "flightNumber": "500",
                            "flightDate": "2014-08-20",
                            "legs": [
                                {
                                    "airlineCodes": {
                                        "operating": "LA",
                                        "marketing": "LA",
                                        "owner": "LA"
                                    },
                                    "departure": {
                                        "airportCode": "SCL",
                                        "blockOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "takeOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "arrival": {
                                        "airportCode": "MIA",
                                        "touchDown": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "blockOn": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "flightServiceType": {
                                        "code": "J",
                                        "description": "Passenger Normal Service",
                                        "routeTypeCode": "INT"
                                    },
                                    "material": {
                                        "aircraftRegistration": "CC-BBD",
                                        "fleet": "B787",
                                        "model": "800"
                                    },
                                    "statusCode": "AA",
                                    "descriptionStatusCode": "Descripcion Status Code AA",
                                    "operationStatusCode": "AA",
                                    "descriptionOperationStatusCode": "Descripcion Operation Status Code AA",
                                    "sufixCode": "AA",
                                    "descriptionSufixCode": "Descripcion Sufix Code AA",
                                    "operationalContingency": [
                                        {
                                            "departureAirportIataCode": "SCL",
                                            "contingencyType": "DELAY",
                                            "contingencyDescription": "Esto es un Atraso",
                                            "statusLog": [
                                                {
                                                    "statusDateTime": "2014-07-27T09:44:36",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-07-27T09:44:36",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-07-25T09:44:36"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-07-25T09:44:36"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                },
                                                {
                                                    "statusDateTime": "2014-07-25T09:44:36",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-07-25T09:44:36",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-07-25T09:44:36"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-07-25T09:44:36"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                }
                                            ],
                                            "protections": [
                                                {
                                                    "airlineCode": "4M",
                                                    "flightNumber": "465",
                                                    "flightDate": "2014-07-25",
                                                    "departureAirportIataCode": "SCL"
                                                },
                                                {
                                                    "airlineCode": "4M",
                                                    "flightNumber": "465",
                                                    "flightDate": "2014-07-25",
                                                    "departureAirportIataCode": "SCL"
                                                }
                                            ]
                                        }
                                    ],
                                    "gateInformation": {
                                        "gateNumber": "17",
                                        "gateDescription": "Puerta de Embarque 17"
                                    }
                                },
                                {
                                    "airlineCodes": {
                                        "operating": "LA",
                                        "marketing": "LA",
                                        "owner": "LA"
                                    },
                                    "departure": {
                                        "airportCode": "SCL",
                                        "blockOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "takeOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "arrival": {
                                        "airportCode": "MIA",
                                        "touchDown": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "blockOn": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "flightServiceType": {
                                        "code": "J",
                                        "description": "Passenger Normal Service",
                                        "routeTypeCode": "INT"
                                    },
                                    "material": {
                                        "aircraftRegistration": "CC-BBD",
                                        "fleet": "B787",
                                        "model": "800"
                                    },
                                    "statusCode": "AA",
                                    "descriptionStatusCode": "Descripcion Status Code AA",
                                    "operationStatusCode": "AA",
                                    "descriptionOperationStatusCode": "Descripcion Operation Status Code AA",
                                    "sufixCode": "AA",
                                    "descriptionSufixCode": "Descripcion Sufix Code AA",
                                    "operationalContingency": [
                                        {
                                            "departureAirportIataCode": "SCL",
                                            "contingencyType": "DELAY",
                                            "contingencyDescription": "Esto es un Atraso",
                                            "statusLog": [
                                                {
                                                    "statusDateTime": "2014-08-20T10:40",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-08-20T10:40",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                },
                                                {
                                                    "statusDateTime": "25-07-2014 09:44:36",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-08-20T10:40",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                }
                                            ],
                                            "protections": [
                                                {
                                                    "airlineCode": "4M",
                                                    "flightNumber": "465",
                                                    "flightDate": "2014-08-20",
                                                    "departureAirportIataCode": "SCL"
                                                },
                                                {
                                                    "airlineCode": "4M",
                                                    "flightNumber": "465",
                                                    "flightDate": "2014-08-20",
                                                    "departureAirportIataCode": "SCL"
                                                }
                                            ]
                                        }
                                    ],
                                    "gateInformation": {
                                        "gateNumber": "17",
                                        "gateDescription": "Puerta de Embarque 17"
                                    }
                                }
                            ]
                        },
                        {
                            "airlineCode": "JJ",
                            "flightNumber": "8029",
                            "flightDate": "20-08-2014",
                            "legs": [
                                {
                                    "airlineCodes": {
                                        "operating": "JJ",
                                        "marketing": "JJ",
                                        "owner": "JJ"
                                    },
                                    "departure": {
                                        "airportCode": "SCL",
                                        "blockOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "takeOff": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "arrival": {
                                        "airportCode": "GRU",
                                        "touchDown": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        },
                                        "blockOn": {
                                            "scheduleDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "realDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            },
                                            "estimatedDateTime": {
                                                "utc": "2014-08-20T10:40Z",
                                                "local": "2014-08-20T10:40"
                                            }
                                        }
                                    },
                                    "flightServiceType": {
                                        "code": "J",
                                        "description": "Passenger Normal Service",
                                        "routeTypeCode": "INT"
                                    },
                                    "material": {
                                        "aircraftRegistration": "PR-MAZ",
                                        "fleet": "A320",
                                        "model": "200"
                                    },
                                    "statusCode": "AA",
                                    "descriptionStatusCode": "Descripcion Status Code AA",
                                    "operationStatusCode": "AA",
                                    "descriptionOperationStatusCode": "Descripcion Operation Status Code AA",
                                    "sufixCode": "AA",
                                    "descriptionSufixCode": "Descripcion Sufix Code AA",
                                    "operationalContingency": [
                                        {
                                            "departureAirportIataCode": "SCL",
                                            "contingencyType": "DELAY",
                                            "contingencyDescription": "Esto es un Atraso",
                                            "statusLog": [
                                                {
                                                    "statusDateTime": "2014-08-20T10:40",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-08-20T10:40",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                },
                                                {
                                                    "statusDateTime": "2014-08-20T10:40",
                                                    "contingencyStatusCode": "ED-1",
                                                    "informedDateTime": "2014-08-20T10:40",
                                                    "cause": {
                                                        "causeCode": "causa1",
                                                        "causeOtherText": "otra causa 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "reason": {
                                                        "reasonCode": "razon1",
                                                        "reasonOtherText": "otra razon 1",
                                                        "inputDateTime": "2014-08-20"
                                                    },
                                                    "basicServices": [
                                                        {
                                                            "basicServiceType": "servicio 1",
                                                            "basicServiceDescription": "descripcion del servicio 1",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        },
                                                        {
                                                            "basicServiceType": "servicio 2",
                                                            "basicServiceDescription": "descripcion del servicio 2",
                                                            "isServiceApplies": "true",
                                                            "isServiceExceptions": "false",
                                                            "isServiceGranted": "true",
                                                            "originQuantity": "5",
                                                            "destinationQuantity": "10"
                                                        }
                                                    ],
                                                    "notifications": {
                                                        "isNotifiedInAirport": "false",
                                                        "airportNotificationText": "usted será notificado en el aeropuerto",
                                                        "isNotifiedOutsideAirport": "true",
                                                        "outsideAirportNotificationText": "usted sera notificado fuera del aeropuerto"
                                                    }
                                                }
                                            ],
                                            "protections": [
                                                {
                                                    "airlineCode": "XL",
                                                    "flightNumber": "100",
                                                    "flightDate": "2014-08-20",
                                                    "departureAirportCode": "SCL"
                                                },
                                                {
                                                    "airlineCode": "XL",
                                                    "flightNumber": "101",
                                                    "flightDate": "2014-08-20",
                                                    "departureAirportCode": "SCL"
                                                }
                                            ]
                                        }
                                    ],
                                    "gateInformation": {
                                        "gateNumber": "190",
                                        "gateDescription": "Puerta de Embarque 190"
                                    }
                                }
                            ]
                        }
                    ]
                }
            }
            
                
                
+ Response 500 (application/json)

    + Header

            X-My-Header: The Value
            
    + Body   
    
            {
                "status": {
                    "code": "500",
                    "message": "ERROR",
                    "nativeMessage": "Runtime Exception"
                }
            }
        